version: '3'

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
