version: '3'

services:
  haproxy:
    image: haproxy:alpine
    depends_on:
      - nginx_1
      - nginx_2
    ports:
      - 80:80
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  haproxy-exporter:
    image: quay.io/prometheus/haproxy-exporter:v0.9.0
    depends_on:
      - haproxy
    command: --haproxy.scrape-uri="http://haproxy:9000/stats?;csv"

  nginx_1:
    image: nginx:alpine
    volumes:
      - ./nginx/stub_status.conf:/etc/nginx/conf.d/stub_status.conf:ro

  nginx-exporter_1:
    image: nginx/nginx-prometheus-exporter:0.2.0
    depends_on:
      - nginx_1
    command: -nginx.scrape-uri http://nginx_1:8080/stub_status

  nginx_2:
    image: nginx:alpine
    volumes:
      - ./nginx/stub_status.conf:/etc/nginx/conf.d/stub_status.conf:ro

  nginx-exporter_2:
    image: nginx/nginx-prometheus-exporter:0.2.0
    depends_on:
      - nginx_2
    command: -nginx.scrape-uri http://nginx_2:8080/stub_status

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  redis-exporter:
    image: oliver006/redis_exporter
    depends_on:
      - redis
    environment:
      REDIS_ADDR: redis:6379

  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URL: http://rabbitmq:15672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      PUBLISH_PORT: 9090
      OUTPUT_FORMAT: JSON
      LOG_LEVEL: debug

  node-exporter:
    image: quay.io/prometheus/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /cgroup:/cgroup:ro

  prometheus:
    image: prom/prometheus
    depends_on:
      - nginx-exporter_1
      - nginx-exporter_2
      - rabbitmq-exporter
      - redis-exporter
      - node-exporter
      - cadvisor
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
