global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
        labels:
          group: prometheus

  - job_name: grafana
    static_configs:
      - targets:
        - grafana:3000
        labels:
          group: prometheus

  - job_name: docker
    static_configs:
      - targets:
        - cadvisor:8080
        labels:
          group: docker-container

  - job_name: docker-host
    static_configs:
      - targets:
        - node-exporter:9100
        labels:
          group: docker-host
